// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVbkHibX4erFPvHFQmcde3IiuNzeOqEXM',
    appId: '1:654670698252:android:826280f3fc5318a42c9b29',
    messagingSenderId: '654670698252',
    projectId: 'risenger',
    storageBucket: 'risenger.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtDHDnvixWuEoVEF12sA_jnKUbl_HYT4U',
    appId: '1:654670698252:ios:6aebe43b97dc6c5c2c9b29',
    messagingSenderId: '654670698252',
    projectId: 'risenger',
    storageBucket: 'risenger.appspot.com',
    iosBundleId: 'com.example.risenger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQrOgWcvjcJ_PEC1OXbxjax3gx_OX95xY',
    appId: '1:654670698252:web:bf3128f53be3874d2c9b29',
    messagingSenderId: '654670698252',
    projectId: 'risenger',
    authDomain: 'risenger.firebaseapp.com',
    storageBucket: 'risenger.appspot.com',
    measurementId: 'G-H1P8QY1T75',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQrOgWcvjcJ_PEC1OXbxjax3gx_OX95xY',
    appId: '1:654670698252:web:bf3128f53be3874d2c9b29',
    messagingSenderId: '654670698252',
    projectId: 'risenger',
    authDomain: 'risenger.firebaseapp.com',
    storageBucket: 'risenger.appspot.com',
    measurementId: 'G-H1P8QY1T75',
  );

}